apiVersion: v1
kind: Service
apiVersion: v1
metadata:
  name: my-app
spec:
  selector:
    app: my-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080  
  type: LoadBalancer
  
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app
        version: v1
    spec:
      containers:
      - name: edu-api
        image: saturn203/my-app:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
 
